### ISSUE TITLE
OpenSSL TLS provider not working correctly

### ISSUE THREAD

**Issue by tripleslash** [an-tao/trantor#304]
When a HTTPs response with a large content body is sent, then not all bytes will be transferred and the connection will hang indefinitely until it reaches a timeout.

Example request:

> curl -X 'GET' -k \
  'https://192.168.200.232/v2/endpoint' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic dGVzdDo=' --trace-time -v
Note: Unnecessary use of -X or --request, GET is already inferred.
15:44:55.711265 *   Trying 192.168.200.232:443...
15:44:55.717252 * Connected to 192.168.200.232 (192.168.200.232) port 443 (#0)
15:44:55.719318 * ALPN, offering h2
15:44:55.719346 * ALPN, offering http/1.1
15:44:55.719472 * TLSv1.0 (OUT), TLS header, Certificate Status (22):
15:44:55.719503 * TLSv1.3 (OUT), TLS handshake, Client hello (1):
15:44:55.761049 * TLSv1.2 (IN), TLS header, Certificate Status (22):
15:44:55.761226 * TLSv1.3 (IN), TLS handshake, Server hello (2):
15:44:55.761775 * TLSv1.2 (IN), TLS header, Finished (20):
15:44:55.761849 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.761886 * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
15:44:55.761913 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.761999 * TLSv1.3 (IN), TLS handshake, Certificate (11):
15:44:55.763293 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.763344 * TLSv1.3 (IN), TLS handshake, CERT verify (15):
15:44:55.763410 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.763449 * TLSv1.3 (IN), TLS handshake, Finished (20):
15:44:55.763489 * TLSv1.2 (OUT), TLS header, Finished (20):
15:44:55.763513 * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
15:44:55.763558 * TLSv1.2 (OUT), TLS header, Supplemental data (23):
15:44:55.763591 * TLSv1.3 (OUT), TLS handshake, Finished (20):
15:44:55.763633 * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
15:44:55.763656 * ALPN, server did not agree to a protocol
15:44:55.763675 * Server certificate:
15:44:55.763690 *  subject: <snip>
15:44:55.763699 *  start date: Oct  4 08:46:14 2023 GMT
15:44:55.763707 *  expire date: Sep 10 08:46:14 2123 GMT
15:44:55.763722 *  issuer: <snip>
15:44:55.763752 *  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
15:44:55.763795 * TLSv1.2 (OUT), TLS header, Supplemental data (23):
15:44:55.763831 > GET /v2/endpoint HTTP/1.1
15:44:55.763831 > Host: 192.168.200.232
15:44:55.763831 > User-Agent: curl/7.81.0
15:44:55.763831 > accept: application/json
15:44:55.763831 > Authorization: Basic dGVzdDo=
15:44:55.763831 >
15:44:55.776094 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.776234 * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
15:44:55.776353 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:55.776497 * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
15:44:55.776742 * old SSL session ID is stale, removing
15:44:56.901714 * TLSv1.2 (IN), TLS header, Supplemental data (23):
15:44:56.910324 * Mark bundle as not supporting multiuse
15:44:56.910420 < HTTP/1.1 200 OK
15:44:56.910559 < content-length: 56531
15:44:56.910639 < content-type: application/json; charset=utf-8
15:44:56.910772 < server: backend-api/0.1.0.6822
15:44:56.910938 < access-control-allow-origin: *
15:44:56.911114 < date: Mon, 27 Nov 2023 14:44:52 GMT
15:44:56.911246 <
{"json_content_that_will_be_cut_off
15:44:56.912609 * TLSv1.2 (IN), TLS header, Supplemental data (23):
^C ////// <<<< timeout

Is it possible that the last chunk of data is not flushed to the output?

**Comment by an-tao** [comment]
Which version of trantor or drogon did you use?

**Comment by tripleslash** [comment]
My trantor lib is built from commit tree https://github.com/an-tao/trantor/tree/26a599857a2fa5d61823ef85012e3d9123d5a675 as of right now and drogon is built from tag 1.9.0 tree

**Comment by tripleslash** [comment]
If I keep the connection open and don't cancel it I get the following curl error after 30 seconds:

![image](https://github.com/an-tao/trantor/assets/4272703/7ab02374-ce54-443b-b530-10ff5c5b2949)

**Comment by tripleslash** [comment]
Is it possible that the last chunk of data is not properly flushed to the TCP socket when the HTTP connection is closed? Maybe there are still some bytes pending and trantor does not wait until it is fully transferred to the client before closing the connection?

**Comment by an-tao** [comment]
I can't reproduce this error in my environment.
```
curl -X 'GET' -k https://10.0.0.100:1100/test -v -s -o /dev/null
*   Trying 10.0.0.100:1100...
* Connected to 10.0.0.100 (10.0.0.100) port 1100 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1470 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [520 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.2 (OUT), TLS header, Finished (20):
} [5 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=TW; ST=Taipei; L=Taipei; O=Martin; OU=Martin; CN=Martin
*  start date: Feb  9 12:37:34 2023 GMT
*  expire date: Jan 16 12:37:34 2123 GMT
*  issuer: C=TW; ST=Taipei; L=Taipei; O=Martin; OU=Martin; CN=Martin
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> GET /test HTTP/1.1
> Host: 10.0.0.100:1100
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [233 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [233 bytes data]
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 56531
< content-type: text/html; charset=utf-8
< server: drogon/1.9.1
< date: Mon, 27 Nov 2023 15:49:03 GMT
< 
{ [16243 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* Connection #0 to host 10.0.0.100 left intact
```
@marty1885 What do you think might be causing this issue?

**Comment by tripleslash** [comment]
Also happens with latest trantor (v1.5.15) and drogon (v1.9.1)

**Comment by marty1885** [comment]
Me too I can't replicate the issue what so ever. This is what is blocking me from fixing it. :(

@tripleslash Can you share details about the environment you are using? OpenSSL version, compiler, distro, etc.. And if you have Botan3. Can you try Botan 3 and see if the same thing is happening?

**Comment by tripleslash** [comment]
Custom built Linux BSP with Kernel 6.5.12 and OpenSSL 3.1.0. I cant change my TLS Provider because many other applications on my system depend on OpenSSL

**Comment by tripleslash** [comment]
> 20231128 08:24:30.062488 UTC 4347 TRACE [newFileResponse] send http file:/var/www//ui/assets/images/wasthec_loadingd80ae7c176ae41d8797c.png offset 0 length 0 - HttpResponseImpl.cc:296
20231128 08:24:30.063095 UTC 4347 TRACE [sendStaticFileResponse] Save in cache for 5 seconds - StaticFileRouter.cc:562
20231128 08:24:30.063734 UTC 4347 TRACE [renderToBuffer] reponse(no body):HTTP/1.1 200 OK
content-length: 51581
content-type: image/png
server: washtec-backend-api/0.1.0.6824
access-control-allow-origin: *
accept-range: bytes
expires: Thu, 01 Jan 1970 00:00:00 GMT
last-modified: Mon, 27 Nov 2023 15:39:30 GMT
date: Tue, 28 Nov 2023 08:24:30 GMT

 - HttpResponseImpl.cc:704
20231128 08:24:30.069186 UTC 4347 TRACE [sendFileInLoop] send file in loop - TcpConnectionImpl.cc:1133
20231128 08:24:30.086815 UTC 4347 TRACE [sendFileInLoop] send file in loop: break on socket buffer full (?) - TcpConnectionImpl.cc:1215
20231128 08:24:30.086909 UTC 4347 TRACE [sendFileInLoop] send file in loop: return on loop exit - TcpConnectionImpl.cc:1234
20231128 08:24:30.093514 UTC 4347 TRACE [sendFileInLoop] send file in loop - TcpConnectionImpl.cc:1133
20231128 08:24:30.107780 UTC 4347 TRACE [sendFileInLoop] send file in loop: break on socket buffer full (?) - TcpConnectionImpl.cc:1215
20231128 08:24:30.107874 UTC 4347 TRACE [sendFileInLoop] send file in loop: return on loop exit - TcpConnectionImpl.cc:1234
20231128 08:24:30.124704 UTC 4347 TRACE [sendFileInLoop] send file in loop - TcpConnectionImpl.cc:1133
20231128 08:24:30.155241 UTC 4347 TRACE [sendFileInLoop] send file in loop: break on socket buffer full (?) - TcpConnectionImpl.cc:1215
20231128 08:24:30.155333 UTC 4347 TRACE [sendFileInLoop] send file in loop: return on loop exit - TcpConnectionImpl.cc:1234
20231128 08:24:30.181652 UTC 4347 TRACE [sendFileInLoop] send file in loop - TcpConnectionImpl.cc:1133
20231128 08:24:30.223903 UTC 4347 TRACE [sendFileInLoop] send file in loop: return on loop exit - TcpConnectionImpl.cc:1234
20231128 08:24:33.879093 UTC 4347 TRACE [operator()] Erase cache - StaticFileRouter.cc:568
20231128 08:24:34.320739 UTC 4347 TRACE [recvData] Received 473 bytes from lower layer - OpenSSLProvider.cc:533
20231128 08:24:34.321107 UTC 4347 TRACE [processApplicationData] Received 451 bytes from SSL - OpenSSLProvider.cc:739

**Comment by an-tao** [comment]
Can you test your application in a normal linux x86 server?

**Comment by tripleslash** [comment]
`TRACE [sendFileInLoop] send file in loop: break on socket buffer full (?) - TcpConnectionImpl.cc:1215`
this line always eems to happen when the issue appears

**Comment by an-tao** [comment]
> `TRACE [sendFileInLoop] send file in loop: break on socket buffer full (?) - TcpConnectionImpl.cc:1215` this line always seems to happen when the issue appears

You could modify that line to output the error number.

**Comment by marty1885** [comment]
That is normal and expected. That sounds like the async socket is full and we are waiting for the OS to make the socket writable again. Hmm.... I agree this could solved by your proposal. But I really need to replicate the bug locally to fix it.

@tripleslash You should be able to switch the TLS provider. Other code can keep using OpenSSL. Trantor will simply use Botan3 for the underlying. Unless you are setting OpenSSL specific configuration commands.

**Comment by tripleslash** [comment]
`Resource temporarily unavailable (errno=11) send file in loop: break on socket buffer full (?) - 11`

errno = 11

**Comment by tripleslash** [comment]
> That is normal and expected. That sounds like the async socket is full and we are waiting for the OS to make the socket writable again. Hmm.... I agree this could solved by your proposal. But I really need to replicate the bug locally to fix it.
> 
> @tripleslash You should be able to switch the TLS provider. Other code can keep using OpenSSL. Trantor will simply use Botan3 for the underlying. Unless you are setting OpenSSL specific configuration commands.

It is quite some effort to add a new BSP build rule to build an entirely new TLS provider. Apart from that I really would like to use the same TLS implementation across the entire system

**Comment by tripleslash** [comment]
The issue seems to happen more frequently when you try to connect to the device from outside the intranet or over SSH proxies for example. In intranet it is hard to reproduce I agree.

**Comment by marty1885** [comment]
@tripleslash Sorry getting back to you late. Can you try the latest master? We fixed a bug that may be related to this bug report.

**Comment by an-tao** [comment]
I think the [PR](https://github.com/an-tao/trantor/pull/312) may resolve this problem, @tripleslash would u please check it out?

**Comment by tripleslash** [comment]
> I think the [PR](https://github.com/an-tao/trantor/pull/312) may resolve this problem, @tripleslash would u please check it out?

I can confirm that the issue seems to be gone with the refactored trantor API ! @an-tao

**Comment by tripleslash** [comment]
another update on this: i was able to still reproduce this error but it seems to happen much more rarely now with the trantor refactoring

**Comment by an-tao** [comment]
@tripleslash Thanks so much for your test on this. I added some debug logs to the destructor of the Tcp Connection Impl class (https://github.com/an-tao/trantor/pull/312/commits/6f854779ecaa96a43a249265045b263328d49e3f). 
please check it out. when the hanging occurs, disconnect from client, and find those logs on server, let's figure it out.

**Comment by CPPBS** [comment]
### A temporary workaround using libcurl

### 基于 libcurl 的临时解决方案

---

We have also been blocked by this bug when receiving large HTTPS responses – the connection hangs and the data is incomplete.

As a stopgap solution before an official fix lands, we implemented an alternative `HttpClient` that **completely bypasses trantor's TLS/network stack** and uses libcurl (`curl_easy_perform`) in a dedicated worker thread.

This approach has allowed us to continue development without waiting for the underlying issue to be resolved. The implementation is API‑compatible with `drogon::HttpClient`, so switching between the two is straightforward.

**How to use it**  
Simply call `oem::CurlHttpClient::newHttpClient("https://your-server.com")` and send requests as you normally would.

**Important caveats**

- This is a **temporary workaround**, not a production‑grade replacement.
- Each request creates a new libcurl handle – no connection reuse or keep‑alive.
- Cookie management, pipelining, client certificates, and most advanced features are not implemented.
- The `timeout` parameter is ignored (currently fixed at 30 seconds; you can modify it).
- Callbacks are invoked from the worker thread, **not** from the `EventLoop` thread – be careful with thread safety.

We hope this helps unblock other projects. Looking forward to the official fix!

---

我们也遇到了这个 bug 的困扰——在接收较大的 HTTPS 响应时，连接会挂起，数据不完整。

在官方修复之前，我们实现了一个替代的 `HttpClient`，它**完全绕过了 `trantor` 的 TLS/网络栈**，在一个独立的工作线程中直接使用 libcurl（`curl_easy_perform`）。

这个方案让我们能够继续推进项目，而无需等待底层问题的解决。该实现与 `drogon::HttpClient` 的接口兼容，因此可以轻松切换。

**使用方法**  
直接调用 `oem::CurlHttpClient::newHttpClient("https://your-server.com")`，然后像平常一样发送请求即可。

**重要注意事项**

- 这只是一个**临时方案**，不适合作为生产环境的长期替代。
- 每个请求都会新建一个 libcurl 句柄，没有连接复用或 keep‑alive。
- Cookie 管理、管道化、客户端证书以及大多数高级功能均未实现。
- `timeout` 参数被忽略（当前固定为 30 秒，你可以自行修改）。
- 回调函数在工作线程中执行，**而非** `EventLoop` 线程，请注意线程安全。

希望这个方案能帮助其他受阻的项目。期待官方的正式修复！

---

CurlHttpClient.h
```
#pragma once

#include <drogon/HttpClient.h>
#include <drogon/HttpRequest.h>
#include <drogon/HttpResponse.h>
#include <drogon/Cookie.h>
#include <memory>
#include <vector>
#include <string>
#include <functional>
#include <mutex>
#include <thread>
#include <atomic>
#include <queue>
#include <condition_variable>
#include <curl/curl.h>

namespace oem
{

    class CurlHttpClient : public drogon::HttpClient
    {
    public:
        static std::shared_ptr<CurlHttpClient> newHttpClient(
            const std::string &hostString,
            trantor::EventLoop *loop = nullptr,
            bool useOldTLS = false,
            bool validateCert = true);

        void sendRequest(const drogon::HttpRequestPtr &req,
                         const drogon::HttpReqCallback &callback,
                         double timeout = 0) override;

        void sendRequest(const drogon::HttpRequestPtr &req,
                         drogon::HttpReqCallback &&callback,
                         double timeout = 0) override;

        // 其他虚函数（仅保留必要的，其余空实现）
        void setSockOptCallback(std::function<void(int)> cb) override {}
        std::size_t requestsBufferSize() override { return 0; }
        void setPipeliningDepth(size_t depth) override {}
        void enableCookies(bool flag = true) override {}
        void addCookie(const std::string &key, const std::string &value) override {}
        void addCookie(const drogon::Cookie &cookie) override {}
        void setUserAgent(const std::string &userAgent) override {}
        trantor::EventLoop *getLoop() override { return nullptr; }
        size_t bytesSent() const override { return 0; }
        size_t bytesReceived() const override { return 0; }
        std::string host() const override { return domain_; }
        uint16_t port() const override { return port_; }
        bool secure() const override { return useSSL_; }
        void setCertPath(const std::string &cert, const std::string &key) override {}
        void addSSLConfigs(const std::vector<std::pair<std::string, std::string>> &sslConfCmds) override {}

        ~CurlHttpClient() override;

    private:
        struct ParsedUrl
        {
            std::string domain;
            uint16_t port;
            bool useSSL;
        };
        static ParsedUrl parseUrl(const std::string &url);

        static size_t writeCallback(char *ptr, size_t size, size_t nmemb, void *userdata);
        static size_t headerCallback(char *buffer, size_t size, size_t nitems, void *userdata);

        CurlHttpClient(const std::string &domain, uint16_t port, bool useSSL,
                       bool validateCert);

        void workerThread();

        std::string domain_;
        uint16_t port_;
        bool useSSL_;
        bool validateCert_;

        std::atomic<bool> running_{true};
        std::mutex queueMutex_;
        std::queue<std::pair<drogon::HttpRequestPtr, drogon::HttpReqCallback>> pendingQueue_;
        std::condition_variable cv_;
        std::thread worker_;

        static std::once_flag curlInitFlag_;
    };

}
```

CurlHttpClient.cc
```
#include "CurlHttpClient.h"
#include <drogon/HttpTypes.h>
#include <trantor/utils/Logger.h>
#include <sstream>
#include <cstring>

namespace oem
{

    std::once_flag CurlHttpClient::curlInitFlag_;

    CurlHttpClient::ParsedUrl CurlHttpClient::parseUrl(const std::string &url)
    {
        ParsedUrl result;
        std::string tmp = url;
        if (tmp.find("https://") == 0)
        {
            result.useSSL = true;
            tmp = tmp.substr(8);
        }
        else if (tmp.find("http://") == 0)
        {
            result.useSSL = false;
            tmp = tmp.substr(7);
        }
        else
        {
            result.useSSL = false;
        }
        size_t pos = tmp.find('/');
        if (pos != std::string::npos)
            tmp = tmp.substr(0, pos);
        pos = tmp.find(':');
        if (pos != std::string::npos)
        {
            result.domain = tmp.substr(0, pos);
            result.port = static_cast<uint16_t>(std::stoi(tmp.substr(pos + 1)));
        }
        else
        {
            result.domain = tmp;
            result.port = result.useSSL ? 443 : 80;
        }
        return result;
    }

    size_t CurlHttpClient::writeCallback(char *ptr, size_t size, size_t nmemb, void *userdata)
    {
        auto *body = static_cast<std::string *>(userdata);
        size_t total = size * nmemb;
        body->append(ptr, total);
        return total;
    }

    size_t CurlHttpClient::headerCallback(char *buffer, size_t size, size_t nitems, void *userdata)
    {
        auto *headers = static_cast<std::vector<std::string> *>(userdata);
        size_t total = size * nitems;
        std::string line(buffer, total);
        if (!line.empty() && line.back() == '\n')
            line.pop_back();
        if (!line.empty() && line.back() == '\r')
            line.pop_back();
        if (!line.empty())
            headers->push_back(line);
        return total;
    }

    CurlHttpClient::CurlHttpClient(const std::string &domain, uint16_t port, bool useSSL,
                                   bool validateCert)
        : domain_(domain), port_(port), useSSL_(useSSL),
          validateCert_(validateCert)
    {
        std::call_once(curlInitFlag_, curl_global_init, CURL_GLOBAL_ALL);
        worker_ = std::thread(&CurlHttpClient::workerThread, this);
    }

    CurlHttpClient::~CurlHttpClient()
    {
        running_ = false;
        cv_.notify_all();
        if (worker_.joinable())
        {
            worker_.join();
        }
    }

    std::shared_ptr<CurlHttpClient> CurlHttpClient::newHttpClient(
        const std::string &hostString,
        trantor::EventLoop *loop,
        bool useOldTLS,
        bool validateCert)
    {
        auto parsed = parseUrl(hostString);
        auto client = std::shared_ptr<CurlHttpClient>(
            new CurlHttpClient(parsed.domain, parsed.port, parsed.useSSL,
                               validateCert));
        return client;
    }

    void CurlHttpClient::workerThread()
    {
        while (running_)
        {
            drogon::HttpRequestPtr req;
            drogon::HttpReqCallback callback;
            {
                std::unique_lock<std::mutex> lock(queueMutex_);
                if (pendingQueue_.empty())
                {
                    cv_.wait_for(lock, std::chrono::milliseconds(100));
                    continue;
                }
                auto &item = pendingQueue_.front();
                req = item.first;
                callback = std::move(item.second);
                pendingQueue_.pop();
            }

            // 执行请求
            CURL *easy = curl_easy_init();
            if (!easy)
            {
                callback(drogon::ReqResult::NetworkFailure, nullptr);
                continue;
            }

            // 构建完整 URL
            std::string scheme = useSSL_ ? "https" : "http";
            std::string url = scheme + "://" + domain_;
            if ((useSSL_ && port_ != 443) || (!useSSL_ && port_ != 80))
            {
                url += ":" + std::to_string(port_);
            }
            url += req->path();
            if (!req->query().empty())
            {
                url += "?" + req->query();
            }

            curl_easy_setopt(easy, CURLOPT_URL, url.c_str());
            curl_easy_setopt(easy, CURLOPT_TIMEOUT_MS, static_cast<long>(30 * 1000)); // 默认30s

            // SSL 验证
            if (!validateCert_)
            {
                curl_easy_setopt(easy, CURLOPT_SSL_VERIFYPEER, 0L);
                curl_easy_setopt(easy, CURLOPT_SSL_VERIFYHOST, 0L);
            }
            else
            {
                curl_easy_setopt(easy, CURLOPT_SSL_VERIFYPEER, 1L);
                curl_easy_setopt(easy, CURLOPT_SSL_VERIFYHOST, 2L);
#ifdef _WIN32
                // Windows 上使用系统 CA 存储
                curl_easy_setopt(easy, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);
#endif
            }

            // 方法
            auto method = req->method();
            if (method == drogon::Get)
            {
                curl_easy_setopt(easy, CURLOPT_HTTPGET, 1L);
            }
            else if (method == drogon::Post)
            {
                curl_easy_setopt(easy, CURLOPT_POST, 1L);
                curl_easy_setopt(easy, CURLOPT_POSTFIELDS, req->getBody().data());
                curl_easy_setopt(easy, CURLOPT_POSTFIELDSIZE, req->getBody().size());
            }
            else
            {
                const char *m = (method == drogon::Put) ? "PUT" : (method == drogon::Delete) ? "DELETE"
                                                              : (method == drogon::Head)     ? "HEAD"
                                                              : (method == drogon::Options)  ? "OPTIONS"
                                                              : (method == drogon::Patch)    ? "PATCH"
                                                                                             : "GET";
                curl_easy_setopt(easy, CURLOPT_CUSTOMREQUEST, m);
                if (method == drogon::Put || method == drogon::Patch)
                {
                    curl_easy_setopt(easy, CURLOPT_POSTFIELDS, req->getBody().data());
                    curl_easy_setopt(easy, CURLOPT_POSTFIELDSIZE, req->getBody().size());
                }
            }

            // Headers
            struct curl_slist *headers = nullptr;
            for (const auto &h : req->headers())
            {
                std::string header = h.first + ": " + h.second;
                headers = curl_slist_append(headers, header.c_str());
            }
            if (headers)
            {
                curl_easy_setopt(easy, CURLOPT_HTTPHEADER, headers);
            }

            // Response data
            std::string responseBody;
            std::vector<std::string> responseHeaders;
            curl_easy_setopt(easy, CURLOPT_WRITEFUNCTION, writeCallback);
            curl_easy_setopt(easy, CURLOPT_WRITEDATA, &responseBody);
            curl_easy_setopt(easy, CURLOPT_HEADERFUNCTION, headerCallback);
            curl_easy_setopt(easy, CURLOPT_HEADERDATA, &responseHeaders);

            CURLcode res = curl_easy_perform(easy);
            long httpCode = 0;
            curl_easy_getinfo(easy, CURLINFO_RESPONSE_CODE, &httpCode);

            drogon::ReqResult result;
            if (res == CURLE_OK && httpCode > 0)
            {
                result = drogon::ReqResult::Ok;
            }
            else if (res == CURLE_OPERATION_TIMEDOUT)
            {
                result = drogon::ReqResult::Timeout;
            }
            else if (res == CURLE_COULDNT_RESOLVE_HOST || res == CURLE_COULDNT_RESOLVE_PROXY)
            {
                result = drogon::ReqResult::BadServerAddress;
            }
            else if (res == CURLE_COULDNT_CONNECT)
            {
                result = drogon::ReqResult::NetworkFailure;
            }
            else
            {
                result = drogon::ReqResult::NetworkFailure;
            }

            auto resp = drogon::HttpResponse::newHttpResponse();
            if (result == drogon::ReqResult::Ok)
            {
                resp->setStatusCode(static_cast<drogon::HttpStatusCode>(httpCode));
                resp->setBody(responseBody);
                for (const auto &line : responseHeaders)
                {
                    auto colon = line.find(':');
                    if (colon != std::string::npos)
                    {
                        std::string key = line.substr(0, colon);
                        std::string value = line.substr(colon + 2);
                        resp->addHeader(key, value);
                    }
                }
            }

            callback(result, resp);
            curl_slist_free_all(headers);
            curl_easy_cleanup(easy);
        }
    }

    void CurlHttpClient::sendRequest(const drogon::HttpRequestPtr &req,
                                     const drogon::HttpReqCallback &callback,
                                     double timeout)
    {
        sendRequest(req, drogon::HttpReqCallback(callback), timeout);
    }

    void CurlHttpClient::sendRequest(const drogon::HttpRequestPtr &req,
                                     drogon::HttpReqCallback &&callback,
                                     double timeout)
    {
        {
            std::lock_guard<std::mutex> lock(queueMutex_);
            pendingQueue_.push({req, std::move(callback)});
        }
        cv_.notify_one();
    }

}
```
